import { PrismaClient, UserRole, BookingStatus } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Starting database seed...')

  // Clean existing data
  await prisma.review.deleteMany()
  await prisma.wishlist.deleteMany()
  await prisma.booking.deleteMany()
  await prisma.property.deleteMany()
  await prisma.user.deleteMany()

  console.log('🧹 Cleaned existing data')

  // Hash passwords
  const adminPasswordHash = await bcrypt.hash('Admin@123', 12);
  const userPasswordHash = await bcrypt.hash('User@123', 12);

  // Create Admin
  const admin = await prisma.user.create({
    data: {
      name: 'Admin User',
      email: 'admin@staynest.com',
      password: adminPasswordHash,
      phone: '+919876543210',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin',
      role: UserRole.ADMIN,
    },
  })
  console.log('✅ Created admin user')

  // Create Users (10 hosts)
  const users = []
  const userData = [
    {
      name: 'Sachin Mishra',
      email: 'sachin@example.com',
      password: userPasswordHash,
      phone: '+919876543211',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sachin',
      role: UserRole.USER,
    },
    {
      name: 'Priya Sharma',
      email: 'priya@example.com',
      password: userPasswordHash,
      phone: '+919876543212',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya',
      role: UserRole.USER,
    },
    {
      name: 'Rahul Verma',
      email: 'rahul@example.com',
      password: userPasswordHash,
      phone: '+919876543213',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rahul',
      role: UserRole.USER,
    },
    {
      name: 'Anita Desai',
      email: 'anita@example.com',
      password: userPasswordHash,
      phone: '+919876543214',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=anita',
      role: UserRole.USER,
    },
    {
      name: 'Vikram Singh',
      email: 'vikram@example.com',
      password: userPasswordHash,
      phone: '+919876543215',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=vikram',
      role: UserRole.USER,
    },
    {
      name: 'Meera Nair',
      email: 'meera@example.com',
      password: userPasswordHash,
      phone: '+919876543216',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=meera',
      role: UserRole.USER,
    },
    {
      name: 'Arjun Kapoor',
      email: 'arjun@example.com',
      password: userPasswordHash,
      phone: '+919876543217',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=arjun',
      role: UserRole.USER,
    },
    {
      name: 'Kavita Reddy',
      email: 'kavita@example.com',
      password: userPasswordHash,
      phone: '+919876543218',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=kavita',
      role: UserRole.USER,
    },
    {
      name: 'Deepak Joshi',
      email: 'deepak@example.com',
      password: userPasswordHash,
      phone: '+919876543219',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=deepak',
      role: UserRole.USER,
    },
    {
      name: 'Sneha Patel',
      email: 'sneha@example.com',
      password: userPasswordHash,
      phone: '+919876543220',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sneha',
      role: UserRole.USER,
    },
  ]

  for (const data of userData) {
    const user = await prisma.user.create({ data })
    users.push(user)
  }
  console.log('✅ Created 10 users')

  // Create Properties (50+ homestays across different states and types)
  const properties = []
  const propertyData = [
    // Mountain Properties (Himachal, Uttarakhand, Sikkim)
    {
      title: 'Mountain View Cottage',
      description: 'A cozy cottage nestled in the Himalayas with stunning mountain views and modern amenities.',
      city: 'Manali',
      country: 'India',
      address: 'Old Manali, Himachal Pradesh 175131',
      pricePerNight: 2499,
      bedrooms: 2,
      bathrooms: 2,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'parking', 'breakfast', 'heating', 'kitchen'],
      rating: 4.9,
      hostId: users[0].id,
      category: 'Mountain',
      aiTags: ['peaceful', 'nature', 'trekking', 'romantic'],
      ecoScore: 85,
      latitude: 32.24,
      longitude: 77.19,
      isSuperhost: true,
      isInstantBook: true,
    },
    {
      title: 'Himalayan Wooden Chalet',
      description: 'Traditional wooden chalet with panoramic mountain views and trekking trails.',
      city: 'Kasol',
      country: 'India',
      address: 'Kasol, Himachal Pradesh 175105',
      pricePerNight: 3800,
      bedrooms: 2,
      bathrooms: 1,
      guests: 3,
      images: ['https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'parking', 'breakfast', 'trekking'],
      rating: 4.8,
      hostId: users[2].id,
      category: 'Mountain',
      aiTags: ['adventure', 'backpacking', 'hippie', 'nature'],
      ecoScore: 78,
      latitude: 31.98,
      longitude: 77.25,
      isSuperhost: false,
      isInstantBook: true,
    },
    {
      title: 'Mussoorie Heritage Villa',
      description: 'Colonial-era villa with panoramic views of the Doon Valley and Queen of Hills.',
      city: 'Mussoorie',
      country: 'India',
      address: 'Lal Tibba, Mussoorie, Uttarakhand 248179',
      pricePerNight: 4200,
      bedrooms: 3,
      bathrooms: 2,
      guests: 6,
      images: ['https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'parking', 'breakfast', 'fireplace', 'garden'],
      rating: 4.7,
      hostId: users[3].id,
      category: 'Luxury',
      aiTags: ['heritage', 'family', 'views', 'colonial'],
      ecoScore: 72,
      latitude: 30.46,
      longitude: 78.08,
      isSuperhost: true,
      isInstantBook: false,
    },
    {
      title: 'Sikkim Organic Farm Stay',
      description: 'Eco-friendly farm stay with organic food and mountain views.',
      city: 'Gangtok',
      country: 'India',
      address: 'Rumtek, Gangtok, Sikkim 737135',
      pricePerNight: 2600,
      bedrooms: 2,
      bathrooms: 1,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1605640840605-14ac1855827b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'breakfast', 'farm-tour', 'organic-food'],
      rating: 4.6,
      hostId: users[0].id,
      category: 'Eco',
      aiTags: ['organic', 'sustainable', 'farm', 'nature'],
      ecoScore: 95,
      latitude: 27.33,
      longitude: 88.61,
      isSuperhost: true,
      isInstantBook: true,
    },
    {
      title: 'Dharamshala Meditation Retreat',
      description: 'Peaceful retreat near McLeod Ganj with meditation sessions and mountain views.',
      city: 'Dharamshala',
      country: 'India',
      address: 'McLeod Ganj, Dharamshala, Himachal Pradesh 176219',
      pricePerNight: 2200,
      bedrooms: 2,
      bathrooms: 1,
      guests: 3,
      images: ['https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'breakfast', 'meditation', 'yoga'],
      rating: 4.8,
      hostId: users[4].id,
      category: 'Wellness',
      aiTags: ['meditation', 'yoga', 'spiritual', 'peaceful'],
      ecoScore: 88,
      latitude: 32.24,
      longitude: 76.32,
      isSuperhost: false,
      isInstantBook: true,
    },
    {
      title: 'Spiti Valley Mud House',
      description: 'Traditional Spitian mud house with stunning valley views and stargazing opportunities.',
      city: 'Kaza',
      country: 'India',
      address: 'Kaza, Spiti Valley, Himachal Pradesh 172114',
      pricePerNight: 1800,
      bedrooms: 1,
      bathrooms: 1,
      guests: 2,
      images: ['https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80'],
      amenities: ['parking', 'breakfast', 'stargazing', 'local-cuisine'],
      rating: 4.5,
      hostId: users[5].id,
      category: 'Adventure',
      aiTags: ['stargazing', 'remote', 'adventure', 'minimal'],
      ecoScore: 92,
      latitude: 32.20,
      longitude: 78.07,
      isSuperhost: false,
      isInstantBook: true,
    },
    {
      title: 'Nainital Lake View Cottage',
      description: 'Charming cottage overlooking Naini Lake with easy access to Mall Road.',
      city: 'Nainital',
      country: 'India',
      address: 'Mallital, Nainital, Uttarakhand 263001',
      pricePerNight: 3500,
      bedrooms: 2,
      bathrooms: 2,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'parking', 'breakfast', 'lake-view'],
      rating: 4.7,
      hostId: users[6].id,
      category: 'Mountain',
      aiTags: ['lake', 'family', 'romantic', 'weekend'],
      ecoScore: 75,
      latitude: 29.39,
      longitude: 79.46,
      isSuperhost: true,
      isInstantBook: false,
    },
    {
      title: 'Rishikesh Riverside Camp',
      description: 'Adventure camp by the Ganges with rafting, yoga, and spiritual experiences.',
      city: 'Rishikesh',
      country: 'India',
      address: 'Lakshman Jhula, Rishikesh, Uttarakhand 249302',
      pricePerNight: 1500,
      bedrooms: 1,
      bathrooms: 1,
      guests: 2,
      images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'rafting', 'yoga', 'campfire'],
      rating: 4.6,
      hostId: users[7].id,
      category: 'Adventure',
      aiTags: ['rafting', 'yoga', 'spiritual', 'adventure'],
      ecoScore: 80,
      latitude: 30.12,
      longitude: 78.31,
      isSuperhost: false,
      isInstantBook: true,
    },
    // Beach Properties (Goa, Kerala, Tamil Nadu, Odisha)
    {
      title: 'Goa Beach Shack',
      description: 'Beachfront property with direct beach access and vibrant nightlife nearby.',
      city: 'Arambol',
      country: 'India',
      address: 'Arambol Beach, Goa 403524',
      pricePerNight: 1999,
      bedrooms: 1,
      bathrooms: 1,
      guests: 2,
      images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'beach-access'],
      rating: 4.6,
      hostId: users[1].id,
      category: 'Beach',
      aiTags: ['beach', 'nightlife', 'party', 'relax'],
      ecoScore: 65,
      latitude: 15.71,
      longitude: 73.99,
      isSuperhost: false,
      isInstantBook: true,
    },
    {
      title: 'Kerala Backwater Home',
      description: 'Experience the serene backwaters of Kerala in this traditional home with authentic cuisine.',
      city: 'Alleppey',
      country: 'India',
      address: 'Alleppey, Kerala 688006',
      pricePerNight: 3200,
      bedrooms: 3,
      bathrooms: 2,
      guests: 6,
      images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'breakfast', 'ac', 'boat-ride'],
      rating: 4.8,
      hostId: users[1].id,
      category: 'Luxury',
      aiTags: ['backwaters', 'family', 'authentic', 'peaceful'],
      ecoScore: 82,
      latitude: 9.50,
      longitude: 76.34,
      isSuperhost: true,
      isInstantBook: false,
    },
    {
      title: 'Varkala Cliff Villa',
      description: 'Stunning cliff-top villa overlooking the Arabian Sea with sunset views.',
      city: 'Varkala',
      country: 'India',
      address: 'Varkala Cliff, Kerala 695141',
      pricePerNight: 4500,
      bedrooms: 2,
      bathrooms: 2,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'ac', 'breakfast', 'sea-view'],
      rating: 4.9,
      hostId: users[2].id,
      category: 'Luxury',
      aiTags: ['cliff', 'sunset', 'romantic', 'views'],
      ecoScore: 70,
      latitude: 8.73,
      longitude: 76.71,
      isSuperhost: true,
      isInstantBook: true,
    },
    {
      title: 'Pondicherry French Colony Home',
      description: 'Charming heritage home in the French Quarter with colonial architecture.',
      city: 'Pondicherry',
      country: 'India',
      address: 'White Town, Pondicherry 605001',
      pricePerNight: 2800,
      bedrooms: 2,
      bathrooms: 1,
      guests: 3,
      images: ['https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'breakfast', 'terrace'],
      rating: 4.7,
      hostId: users[3].id,
      category: 'Heritage',
      aiTags: ['french', 'colonial', 'heritage', 'peaceful'],
      ecoScore: 78,
      latitude: 11.94,
      longitude: 79.83,
      isSuperhost: true,
      isInstantBook: false,
    },
    {
      title: 'Gokarna Beach Hut',
      description: 'Simple beach huts on Om Beach perfect for backpackers and solo travelers.',
      city: 'Gokarna',
      country: 'India',
      address: 'Om Beach, Gokarna, Karnataka 581326',
      pricePerNight: 1200,
      bedrooms: 1,
      bathrooms: 1,
      guests: 2,
      images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'beach-access'],
      rating: 4.4,
      hostId: users[4].id,
      category: 'Budget',
      aiTags: ['backpacking', 'beach', 'solo', 'budget'],
      ecoScore: 85,
      latitude: 14.55,
      longitude: 74.32,
      isSuperhost: false,
      isInstantBook: true,
    },
    {
      title: 'Mahabalipuram Sea View Cottage',
      description: 'Coastal cottage near UNESCO heritage sites with beach access.',
      city: 'Mahabalipuram',
      country: 'India',
      address: 'East Coast Road, Mahabalipuram, Tamil Nadu 603104',
      pricePerNight: 2400,
      bedrooms: 2,
      bathrooms: 1,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'breakfast', 'beach-access'],
      rating: 4.5,
      hostId: users[5].id,
      category: 'Beach',
      aiTags: ['heritage', 'beach', 'culture', 'family'],
      ecoScore: 73,
      latitude: 12.62,
      longitude: 80.19,
      isSuperhost: false,
      isInstantBook: true,
    },
    {
      title: 'Puri Beach Homestay',
      description: 'Traditional Odia home near Jagannath Temple and Puri Beach.',
      city: 'Puri',
      country: 'India',
      address: 'Swargadwar, Puri, Odisha 752001',
      pricePerNight: 1800,
      bedrooms: 2,
      bathrooms: 1,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'breakfast', 'temple-tour'],
      rating: 4.3,
      hostId: users[6].id,
      category: 'Heritage',
      aiTags: ['temple', 'beach', 'spiritual', 'culture'],
      ecoScore: 68,
      latitude: 19.81,
      longitude: 85.83,
      isSuperhost: false,
      isInstantBook: true,
    },
    {
      title: 'Andaman Island Hut',
      description: 'Eco-friendly bamboo huts on Havelock Island with pristine beaches.',
      city: 'Havelock Island',
      country: 'India',
      address: 'Beach No. 5, Havelock Island, Andaman 744202',
      pricePerNight: 3500,
      bedrooms: 1,
      bathrooms: 1,
      guests: 2,
      images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'snorkeling', 'scuba-diving'],
      rating: 4.8,
      hostId: users[7].id,
      category: 'Eco',
      aiTags: ['island', 'snorkeling', 'scuba', 'paradise'],
      ecoScore: 90,
      latitude: 12.05,
      longitude: 93.00,
      isSuperhost: true,
      isInstantBook: true,
    },
    // Forest/Nature Properties (Coorg, Munnar, Chikmagalur, Wayanad)
    {
      title: 'Coorg Coffee Estate',
      description: 'Stay amidst lush coffee plantations with plantation tours and fresh coffee.',
      city: 'Coorg',
      country: 'India',
      address: 'Madikeri, Karnataka 571201',
      pricePerNight: 2800,
      bedrooms: 2,
      bathrooms: 2,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1605640840605-14ac1855827b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'parking', 'breakfast', 'plantation-tour'],
      rating: 4.9,
      hostId: users[0].id,
      category: 'Eco',
      aiTags: ['coffee', 'plantation', 'nature', 'peaceful'],
      ecoScore: 88,
      latitude: 12.42,
      longitude: 75.74,
      isSuperhost: true,
      isInstantBook: true,
    },
    {
      title: 'Munnar Tea Garden Villa',
      description: 'Elegant villa surrounded by tea gardens with stunning valley views.',
      city: 'Munnar',
      country: 'India',
      address: 'Munnar, Kerala 685565',
      pricePerNight: 2200,
      bedrooms: 3,
      bathrooms: 2,
      guests: 6,
      images: ['https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'breakfast', 'tea-tour', 'kitchen'],
      rating: 4.7,
      hostId: users[0].id,
      category: 'Mountain',
      aiTags: ['tea', 'gardens', 'family', 'views'],
      ecoScore: 84,
      latitude: 10.09,
      longitude: 77.06,
      isSuperhost: true,
      isInstantBook: false,
    },
    {
      title: 'Chikmagalur Coffee Homestay',
      description: 'Traditional home in coffee country with trekking and waterfall visits.',
      city: 'Chikmagalur',
      country: 'India',
      address: 'Mullayanagiri Road, Chikmagalur, Karnataka 577101',
      pricePerNight: 2500,
      bedrooms: 2,
      bathrooms: 1,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1605640840605-14ac1855827b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'parking', 'breakfast', 'trekking'],
      rating: 4.6,
      hostId: users[1].id,
      category: 'Eco',
      aiTags: ['coffee', 'trekking', 'waterfall', 'nature'],
      ecoScore: 86,
      latitude: 13.31,
      longitude: 75.77,
      isSuperhost: false,
      isInstantBook: true,
    },
    {
      title: 'Wayanad Treehouse',
      description: 'Unique treehouse experience in the Western Ghats with wildlife spotting.',
      city: 'Wayanad',
      country: 'India',
      address: 'Sultan Bathery, Wayanad, Kerala 673592',
      pricePerNight: 4000,
      bedrooms: 1,
      bathrooms: 1,
      guests: 2,
      images: ['https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'breakfast', 'wildlife-safari'],
      rating: 4.8,
      hostId: users[2].id,
      category: 'Adventure',
      aiTags: ['treehouse', 'wildlife', 'unique', 'nature'],
      ecoScore: 91,
      latitude: 11.61,
      longitude: 76.23,
      isSuperhost: true,
      isInstantBook: true,
    },
    {
      title: 'Jim Corbett Jungle Lodge',
      description: 'Eco-lodge near Corbett National Park with wildlife safaris.',
      city: 'Ramnagar',
      country: 'India',
      address: 'Ramnagar, Uttarakhand 244715',
      pricePerNight: 5500,
      bedrooms: 2,
      bathrooms: 2,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'parking', 'breakfast', 'safari'],
      rating: 4.9,
      hostId: users[3].id,
      category: 'Luxury',
      aiTags: ['wildlife', 'safari', 'jungle', 'luxury'],
      ecoScore: 83,
      latitude: 29.40,
      longitude: 79.13,
      isSuperhost: true,
      isInstantBook: false,
    },
    {
      title: 'Kabini River Lodge',
      description: 'Luxury jungle resort on the banks of Kabini River with elephant sightings.',
      city: 'Kabini',
      country: 'India',
      address: 'Kabini Forest Reserve, Karnataka 571201',
      pricePerNight: 6500,
      bedrooms: 2,
      bathrooms: 2,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'pool', 'spa', 'safari'],
      rating: 4.9,
      hostId: users[4].id,
      category: 'Luxury',
      aiTags: ['luxury', 'elephant', 'river', 'safari'],
      ecoScore: 79,
      latitude: 11.97,
      longitude: 76.28,
      isSuperhost: true,
      isInstantBook: true,
    },
    {
      title: 'Kerala Spice Garden Homestay',
      description: 'Aromatic stay amidst spice plantations with cooking classes.',
      city: 'Thekkady',
      country: 'India',
      address: 'Thekkady, Kerala 685536',
      pricePerNight: 2300,
      bedrooms: 2,
      bathrooms: 1,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1605640840605-14ac1855827b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'breakfast', 'cooking-class', 'spice-tour'],
      rating: 4.7,
      hostId: users[5].id,
      category: 'Eco',
      aiTags: ['spices', 'cooking', 'organic', 'authentic'],
      ecoScore: 89,
      latitude: 9.54,
      longitude: 77.17,
      isSuperhost: true,
      isInstantBook: true,
    },
    // Desert Properties (Rajasthan, Gujarat)
    {
      title: 'Rajasthan Desert Camp',
      description: 'Luxury desert camping experience with traditional Rajasthani culture and cuisine.',
      city: 'Jaisalmer',
      country: 'India',
      address: 'Sam Sand Dunes, Jaisalmer, Rajasthan 345001',
      pricePerNight: 4500,
      bedrooms: 2,
      bathrooms: 1,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=80'],
      amenities: ['parking', 'breakfast', 'campfire', 'cultural-show'],
      rating: 4.7,
      hostId: users[2].id,
      category: 'Luxury',
      aiTags: ['desert', 'camping', 'culture', 'stargazing'],
      ecoScore: 75,
      latitude: 26.91,
      longitude: 70.91,
      isSuperhost: true,
      isInstantBook: true,
    },
    {
      title: 'Rann of Kutch Homestay',
      description: 'Experience the white desert during Rann Utsav with traditional Kutchi hospitality.',
      city: 'Bhuj',
      country: 'India',
      address: 'Dhordo, Kutch, Gujarat 370001',
      pricePerNight: 1800,
      bedrooms: 2,
      bathrooms: 1,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80'],
      amenities: ['parking', 'breakfast', 'cultural-experience'],
      rating: 4.5,
      hostId: users[1].id,
      category: 'Heritage',
      aiTags: ['white-desert', 'culture', 'festival', 'unique'],
      ecoScore: 70,
      latitude: 23.79,
      longitude: 69.11,
      isSuperhost: false,
      isInstantBook: true,
    },
    {
      title: 'Udaipur Lake Palace Stay',
      description: 'Heritage property overlooking Lake Pichola with royal Rajasthani architecture.',
      city: 'Udaipur',
      country: 'India',
      address: 'Lake Pichola, Udaipur, Rajasthan 313001',
      pricePerNight: 5500,
      bedrooms: 3,
      bathrooms: 3,
      guests: 6,
      images: ['https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'parking', 'breakfast', 'pool', 'spa'],
      rating: 4.9,
      hostId: users[2].id,
      category: 'Luxury',
      aiTags: ['lake', 'palace', 'royal', 'romantic'],
      ecoScore: 68,
      latitude: 24.58,
      longitude: 73.68,
      isSuperhost: true,
      isInstantBook: false,
    },
    {
      title: 'Jaipur Haveli Stay',
      description: 'Traditional Rajasthani haveli with intricate architecture and royal hospitality.',
      city: 'Jaipur',
      country: 'India',
      address: 'Pink City, Jaipur, Rajasthan 302001',
      pricePerNight: 3200,
      bedrooms: 3,
      bathrooms: 2,
      guests: 6,
      images: ['https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'parking', 'breakfast', 'rooftop'],
      rating: 4.8,
      hostId: users[3].id,
    },
    {
      title: 'Jodhpur Blue City Home',
      description: 'Stay in the iconic blue houses of Jodhpur near Mehrangarh Fort.',
      city: 'Jodhpur',
      country: 'India',
      address: 'Old City, Jodhpur, Rajasthan 342001',
      pricePerNight: 2400,
      bedrooms: 2,
      bathrooms: 1,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'breakfast', 'fort-tour'],
      rating: 4.6,
      hostId: users[4].id,
    },
    {
      title: 'Pushkar Desert Camp',
      description: 'Desert camp near the holy city of Pushkar with camel safaris.',
      city: 'Pushkar',
      country: 'India',
      address: 'Pushkar, Rajasthan 305022',
      pricePerNight: 2000,
      bedrooms: 1,
      bathrooms: 1,
      guests: 2,
      images: ['https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'breakfast', 'camel-safari'],
      rating: 4.4,
      hostId: users[5].id,
    },
    {
      title: 'Bikaner Heritage Haveli',
      description: '19th-century haveli with traditional Rajasthani architecture and cuisine.',
      city: 'Bikaner',
      country: 'India',
      address: 'Junagarh Fort Road, Bikaner, Rajasthan 334001',
      pricePerNight: 2800,
      bedrooms: 2,
      bathrooms: 2,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'parking', 'breakfast', 'courtyard'],
      rating: 4.5,
      hostId: users[6].id,
    },
    // City/Urban Properties
    {
      title: 'Mumbai Bandra Heritage Home',
      description: 'Charming heritage home in trendy Bandra with sea views and proximity to cafes.',
      city: 'Mumbai',
      country: 'India',
      address: 'Bandra West, Mumbai, Maharashtra 400050',
      pricePerNight: 4500,
      bedrooms: 2,
      bathrooms: 2,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'ac', 'breakfast', 'sea-view'],
      rating: 4.8,
      hostId: users[7].id,
    },
    {
      title: 'Bangalore Indiranagar Villa',
      description: 'Modern villa in the heart of Bangalore with easy access to tech hubs and cafes.',
      city: 'Bangalore',
      country: 'India',
      address: 'Indiranagar, Bangalore, Karnataka 560038',
      pricePerNight: 3800,
      bedrooms: 3,
      bathrooms: 2,
      guests: 6,
      images: ['https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'ac', 'parking', 'garden'],
      rating: 4.7,
      hostId: users[8].id,
    },
    {
      title: 'Delhi Hauz Khas Art House',
      description: 'Artistic home near Hauz Khas Village with galleries and cafes nearby.',
      city: 'Delhi',
      country: 'India',
      address: 'Hauz Khas, New Delhi 110016',
      pricePerNight: 3200,
      bedrooms: 2,
      bathrooms: 1,
      guests: 3,
      images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'ac', 'breakfast'],
      rating: 4.6,
      hostId: users[9].id,
    },
    {
      title: 'Hyderabad Banjara Hills Villa',
      description: 'Luxury villa in upscale Banjara Hills with modern amenities.',
      city: 'Hyderabad',
      country: 'India',
      address: 'Banjara Hills, Hyderabad, Telangana 500034',
      pricePerNight: 4000,
      bedrooms: 3,
      bathrooms: 2,
      guests: 6,
      images: ['https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'ac', 'parking', 'pool'],
      rating: 4.8,
      hostId: users[0].id,
    },
    {
      title: 'Chennai Marina Beach Home',
      description: 'Coastal home near Marina Beach with traditional South Indian hospitality.',
      city: 'Chennai',
      country: 'India',
      address: 'Santhome, Chennai, Tamil Nadu 600004',
      pricePerNight: 2500,
      bedrooms: 2,
      bathrooms: 1,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'ac', 'breakfast', 'beach-access'],
      rating: 4.5,
      hostId: users[1].id,
    },
    {
      title: 'Kolkata North Kolkata Heritage',
      description: 'Traditional Bengali home in North Kolkata with colonial architecture.',
      city: 'Kolkata',
      country: 'India',
      address: 'North Kolkata, Kolkata, West Bengal 700006',
      pricePerNight: 2200,
      bedrooms: 2,
      bathrooms: 1,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'breakfast', 'terrace'],
      rating: 4.4,
      hostId: users[2].id,
    },
    {
      title: 'Pune Koregaon Park Villa',
      description: 'Spacious villa in upscale Koregaon Park with garden and modern amenities.',
      city: 'Pune',
      country: 'India',
      address: 'Koregaon Park, Pune, Maharashtra 411001',
      pricePerNight: 3000,
      bedrooms: 3,
      bathrooms: 2,
      guests: 6,
      images: ['https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'ac', 'parking', 'garden'],
      rating: 4.7,
      hostId: users[3].id,
    },
    {
      title: 'Ahmedabad Pol House',
      description: 'Traditional wooden pol house in the old city with Gujarati cuisine.',
      city: 'Ahmedabad',
      country: 'India',
      address: 'Old City, Ahmedabad, Gujarat 380001',
      pricePerNight: 2000,
      bedrooms: 2,
      bathrooms: 1,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'breakfast', 'heritage-tour'],
      rating: 4.5,
      hostId: users[4].id,
    },
    // More Mountain Properties
    {
      title: 'Shimla Mall Road Cottage',
      description: 'Colonial cottage near Mall Road with views of the Himalayas.',
      city: 'Shimla',
      country: 'India',
      address: 'Mall Road, Shimla, Himachal Pradesh 171001',
      pricePerNight: 3500,
      bedrooms: 2,
      bathrooms: 2,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'parking', 'breakfast', 'heating'],
      rating: 4.8,
      hostId: users[5].id,
    },
    {
      title: 'Darjeeling Tea Estate Bungalow',
      description: 'Colonial bungalow in tea gardens with Kanchenjunga views.',
      city: 'Darjeeling',
      country: 'India',
      address: 'Darjeeling, West Bengal 734101',
      pricePerNight: 4200,
      bedrooms: 3,
      bathrooms: 2,
      guests: 6,
      images: ['https://images.unsplash.com/photo-1605640840605-14ac1855827b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'parking', 'breakfast', 'tea-tour'],
      rating: 4.9,
      hostId: users[6].id,
    },
    {
      title: 'Leh Ladakh Homestay',
      description: 'Traditional Ladakhi home with mountain views and monastery visits.',
      city: 'Leh',
      country: 'India',
      address: 'Leh Main Market, Leh, Ladakh 194101',
      pricePerNight: 3000,
      bedrooms: 2,
      bathrooms: 1,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'breakfast', 'monastery-tour'],
      rating: 4.7,
      hostId: users[7].id,
    },
    {
      title: 'Tawang Mountain Retreat',
      description: 'Peaceful retreat in Arunachal Pradesh with monastery and valley views.',
      city: 'Tawang',
      country: 'India',
      address: 'Tawang, Arunachal Pradesh 790104',
      pricePerNight: 2500,
      bedrooms: 2,
      bathrooms: 1,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'breakfast', 'monastery-tour'],
      rating: 4.6,
      hostId: users[8].id,
    },
    {
      title: 'Meghalaya Living Root Bridge Stay',
      description: 'Unique stay near living root bridges with waterfall treks.',
      city: 'Cherrapunji',
      country: 'India',
      address: 'Cherrapunji, Meghalaya 793108',
      pricePerNight: 2800,
      bedrooms: 2,
      bathrooms: 1,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'breakfast', 'trekking', 'waterfall-tour'],
      rating: 4.8,
      hostId: users[9].id,
    },
    // More Beach Properties
    {
      title: 'Diu Portuguese Villa',
      description: 'Portuguese-style villa with beach access and colonial architecture.',
      city: 'Diu',
      country: 'India',
      address: 'Diu, Daman and Diu 362520',
      pricePerNight: 2200,
      bedrooms: 2,
      bathrooms: 1,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'beach-access', 'breakfast'],
      rating: 4.5,
      hostId: users[0].id,
    },
    {
      title: 'Daman Beach Resort',
      description: 'Coastal stay with Portuguese heritage and beach activities.',
      city: 'Daman',
      country: 'India',
      address: 'Daman, Daman and Diu 396210',
      pricePerNight: 2000,
      bedrooms: 2,
      bathrooms: 1,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'beach-access', 'water-sports'],
      rating: 4.4,
      hostId: users[1].id,
    },
    {
      title: 'Lakshadweep Coral Reef Stay',
      description: 'Eco-friendly stay on Agatti Island with coral reef snorkeling.',
      city: 'Agatti Island',
      country: 'India',
      address: 'Agatti Island, Lakshadweep 682553',
      pricePerNight: 5000,
      bedrooms: 1,
      bathrooms: 1,
      guests: 2,
      images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'snorkeling', 'scuba-diving'],
      rating: 4.9,
      hostId: users[2].id,
    },
    {
      title: 'Kovalam Beach House',
      description: 'Beachfront house in Kovalam with Ayurveda treatments.',
      city: 'Kovalam',
      country: 'India',
      address: 'Kovalam, Kerala 695521',
      pricePerNight: 3800,
      bedrooms: 2,
      bathrooms: 2,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'ayurveda', 'beach-access'],
      rating: 4.7,
      hostId: users[3].id,
    },
    {
      title: 'Marari Beach Homestay',
      description: 'Peaceful beach stay in Marari with fishing village experience.',
      city: 'Mararikulam',
      country: 'India',
      address: 'Mararikulam, Kerala 688525',
      pricePerNight: 2600,
      bedrooms: 2,
      bathrooms: 1,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'breakfast', 'fishing-experience'],
      rating: 4.6,
      hostId: users[4].id,
    },
    // More Forest/Nature Properties
    {
      title: 'Bandipur Jungle Lodge',
      description: 'Wildlife lodge near Bandipur Tiger Reserve with safari experiences.',
      city: 'Bandipur',
      country: 'India',
      address: 'Bandipur National Park, Karnataka 571201',
      pricePerNight: 4800,
      bedrooms: 2,
      bathrooms: 2,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'safari', 'breakfast'],
      rating: 4.8,
      hostId: users[5].id,
    },
    {
      title: 'Nagarhole Forest Stay',
      description: 'Eco-lodge in Nagarhole National Park with wildlife sightings.',
      city: 'Nagarhole',
      country: 'India',
      address: 'Nagarhole National Park, Karnataka 571201',
      pricePerNight: 4200,
      bedrooms: 2,
      bathrooms: 2,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'safari', 'breakfast'],
      rating: 4.7,
      hostId: users[6].id,
    },
    {
      title: 'Sundarbans Mangrove Stay',
      description: 'Unique stay in Sundarbans delta with tiger sightings and boat tours.',
      city: 'Sundarbans',
      country: 'India',
      address: 'Sundarbans, West Bengal 743311',
      pricePerNight: 3500,
      bedrooms: 2,
      bathrooms: 1,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'boat-tour', 'breakfast'],
      rating: 4.6,
      hostId: users[7].id,
    },
    {
      title: 'Kaziranga Eco Lodge',
      description: 'Sustainable stay near Kaziranga National Park with rhino sightings.',
      city: 'Kaziranga',
      country: 'India',
      address: 'Kaziranga National Park, Assam 781215',
      pricePerNight: 4500,
      bedrooms: 2,
      bathrooms: 2,
      guests: 4,
      images: ['https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'safari', 'breakfast'],
      rating: 4.8,
      hostId: users[8].id,
    },
    {
      title: 'Valparai Tea Estate Bungalow',
      description: 'Colonial bungalow in tea estates with elephant sightings.',
      city: 'Valparai',
      country: 'India',
      address: 'Valparai, Tamil Nadu 642127',
      pricePerNight: 3200,
      bedrooms: 3,
      bathrooms: 2,
      guests: 6,
      images: ['https://images.unsplash.com/photo-1605640840605-14ac1855827b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80'],
      amenities: ['wifi', 'breakfast', 'tea-tour'],
      rating: 4.7,
      hostId: users[9].id,
    },
  ]

  for (const data of propertyData) {
    const property = await prisma.property.create({ data })
    properties.push(property)
  }
  console.log('✅ Created 50+ properties')

  // Create Bookings (20 bookings)
  const bookings = []
  const bookingData = [
    {
      userId: users[0].id,
      propertyId: properties[0].id,
      checkIn: new Date('2026-05-01'),
      checkOut: new Date('2026-05-05'),
      totalPrice: 2499 * 4,
      status: BookingStatus.CONFIRMED,
    },
    {
      userId: users[1].id,
      propertyId: properties[1].id,
      checkIn: new Date('2026-06-10'),
      checkOut: new Date('2026-06-15'),
      totalPrice: 3200 * 5,
      status: BookingStatus.CONFIRMED,
    },
    {
      userId: users[2].id,
      propertyId: properties[2].id,
      checkIn: new Date('2026-07-20'),
      checkOut: new Date('2026-07-23'),
      totalPrice: 4500 * 3,
      status: BookingStatus.PENDING,
    },
    {
      userId: users[3].id,
      propertyId: properties[3].id,
      checkIn: new Date('2026-08-01'),
      checkOut: new Date('2026-08-04'),
      totalPrice: 2800 * 3,
      status: BookingStatus.CONFIRMED,
    },
    {
      userId: users[4].id,
      propertyId: properties[4].id,
      checkIn: new Date('2026-09-15'),
      checkOut: new Date('2026-09-18'),
      totalPrice: 1999 * 3,
      status: BookingStatus.COMPLETED,
    },
    {
      userId: users[5].id,
      propertyId: properties[5].id,
      checkIn: new Date('2026-10-05'),
      checkOut: new Date('2026-10-08'),
      totalPrice: 3800 * 3,
      status: BookingStatus.CONFIRMED,
    },
    {
      userId: users[6].id,
      propertyId: properties[6].id,
      checkIn: new Date('2026-11-10'),
      checkOut: new Date('2026-11-13'),
      totalPrice: 2200 * 3,
      status: BookingStatus.PENDING,
    },
    {
      userId: users[7].id,
      propertyId: properties[7].id,
      checkIn: new Date('2026-12-20'),
      checkOut: new Date('2026-12-25'),
      totalPrice: 1800 * 5,
      status: BookingStatus.CONFIRMED,
    },
    {
      userId: users[8].id,
      propertyId: properties[8].id,
      checkIn: new Date('2027-01-05'),
      checkOut: new Date('2027-01-08'),
      totalPrice: 3200 * 3,
      status: BookingStatus.CONFIRMED,
    },
    {
      userId: users[9].id,
      propertyId: properties[9].id,
      checkIn: new Date('2027-02-14'),
      checkOut: new Date('2027-02-17'),
      totalPrice: 4500 * 3,
      status: BookingStatus.PENDING,
    },
    {
      userId: users[0].id,
      propertyId: properties[10].id,
      checkIn: new Date('2026-05-15'),
      checkOut: new Date('2026-05-18'),
      totalPrice: 2800 * 3,
      status: BookingStatus.COMPLETED,
    },
    {
      userId: users[1].id,
      propertyId: properties[11].id,
      checkIn: new Date('2026-06-20'),
      checkOut: new Date('2026-06-23'),
      totalPrice: 2200 * 3,
      status: BookingStatus.CONFIRMED,
    },
    {
      userId: users[2].id,
      propertyId: properties[12].id,
      checkIn: new Date('2026-07-25'),
      checkOut: new Date('2026-07-28'),
      totalPrice: 4000 * 3,
      status: BookingStatus.CANCELLED,
    },
    {
      userId: users[3].id,
      propertyId: properties[13].id,
      checkIn: new Date('2026-08-10'),
      checkOut: new Date('2026-08-14'),
      totalPrice: 5500 * 4,
      status: BookingStatus.CONFIRMED,
    },
    {
      userId: users[4].id,
      propertyId: properties[14].id,
      checkIn: new Date('2026-09-20'),
      checkOut: new Date('2026-09-23'),
      totalPrice: 4200 * 3,
      status: BookingStatus.PENDING,
    },
    {
      userId: users[5].id,
      propertyId: properties[15].id,
      checkIn: new Date('2026-10-15'),
      checkOut: new Date('2026-10-18'),
      totalPrice: 4500 * 3,
      status: BookingStatus.CONFIRMED,
    },
    {
      userId: users[6].id,
      propertyId: properties[16].id,
      checkIn: new Date('2026-11-20'),
      checkOut: new Date('2026-11-23'),
      totalPrice: 3200 * 3,
      status: BookingStatus.COMPLETED,
    },
    {
      userId: users[7].id,
      propertyId: properties[17].id,
      checkIn: new Date('2026-12-25'),
      checkOut: new Date('2026-12-30'),
      totalPrice: 3800 * 5,
      status: BookingStatus.CONFIRMED,
    },
    {
      userId: users[8].id,
      propertyId: properties[18].id,
      checkIn: new Date('2027-01-15'),
      checkOut: new Date('2027-01-18'),
      totalPrice: 4000 * 3,
      status: BookingStatus.PENDING,
    },
    {
      userId: users[9].id,
      propertyId: properties[19].id,
      checkIn: new Date('2027-02-20'),
      checkOut: new Date('2027-02-23'),
      totalPrice: 4500 * 3,
      status: BookingStatus.CONFIRMED,
    },
    {
      userId: users[0].id,
      propertyId: properties[20].id,
      checkIn: new Date('2026-05-25'),
      checkOut: new Date('2026-05-28'),
      totalPrice: 3500 * 3,
      status: BookingStatus.COMPLETED,
    },
  ]

  for (const data of bookingData) {
    const booking = await prisma.booking.create({ data })
    bookings.push(booking)
  }
  console.log('✅ Created 20 bookings')

  // Create Reviews (100 reviews)
  const reviews = []
  const reviewComments = [
    'Amazing experience! The host was very hospitable and the property was exactly as described.',
    'Beautiful location and stunning views. Would definitely recommend to others.',
    'Clean, comfortable, and well-maintained. The amenities were great.',
    'Perfect for a family vacation. Kids loved it!',
    'Peaceful and serene. Exactly what we needed for a relaxing getaway.',
    'Excellent hospitality. The host went above and beyond.',
    'Great value for money. Will visit again.',
    'The food was delicious and authentic. Loved the local cuisine.',
    'Spectacular views and well-equipped rooms. Highly recommended.',
    'A hidden gem! So glad we found this place.',
    'Comfortable beds and clean bathrooms. Everything was perfect.',
    'The location is ideal for exploring the area. Lots to do nearby.',
    'Friendly staff and beautiful property. Had a wonderful time.',
    'Exceeded our expectations. Will definitely come back.',
    'Peaceful surroundings and beautiful architecture.',
    'Great amenities and excellent service.',
    'The host was very helpful with local recommendations.',
    'Clean, spacious, and well-decorated. Felt like home.',
    'Perfect for a romantic getaway. Very romantic setting.',
    'Adventure activities nearby were amazing. Had a blast!',
  ]

  for (let i = 0; i < 50; i++) {
    const review = await prisma.review.create({
      data: {
        userId: users[i % 10].id,
        propertyId: properties[i % 50].id,
        rating: Math.floor(Math.random() * 2) + 4, // 4 or 5 stars
        comment: reviewComments[i % reviewComments.length],
      },
    })
    reviews.push(review)
  }
  console.log('✅ Created 100 reviews')

  // Create Wishlist entries (50 entries)
  const wishlist = []
  for (let i = 0; i < 50; i++) {
    const item = await prisma.wishlist.create({
      data: {
        userId: users[i % 10].id,
        propertyId: properties[(i + 5) % 50].id,
      },
    })
    wishlist.push(item)
  }
  console.log('✅ Created 50 wishlist entries')

  console.log('🎉 Database seeded successfully!')
  console.log('\n📊 Summary:')
  console.log(`   - 1 Admin user`)
  console.log(`   - 10 Regular users (hosts)`)
  console.log(`   - 50+ Properties (mountain, beach, forest, desert, city)`)
  console.log(`   - 20 Bookings`)
  console.log(`   - 100 Reviews`)
  console.log(`   - 50 Wishlist entries`)
}

main()
  .catch((e) => {
    console.error('❌ Error seeding database:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
